[package]
name = "chip8-interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features=["derive"] }
crossterm = "0.29.0"
ctrlc = "3.5.1"
rand = "0.9.2"
rodio = "0.21.1"
